# 回测配置文件
# 遵循RIPER-5原则：风险优先、最小侵入、可预期性、可扩展性、真实可评估

# 基本设置
basic:
  start_date: "2023-01-01"  # 回测开始日期
  end_date: "2023-12-31"    # 回测结束日期
  initial_balance: 10000    # 初始资金
  benchmark: "BTC/USDT"     # 基准标的
  
# 数据设置
data:
  exchange: "binance"       # 交易所
  symbols:                  # 交易对列表
    - "BTC/USDT"
    - "ETH/USDT"
    - "BNB/USDT"
  timeframes:               # 时间框架列表
    - "1h"
    - "4h"
    - "1d"
  data_dir: "./data"        # 数据目录
  
# 策略设置
strategy:
  name: "GridStrategy"      # 策略名称
  params:                   # 策略参数
    grid_size: 0.01         # 网格大小
    grid_levels: 10         # 网格层数
    order_size: 0.01        # 订单大小
    take_profit: 0.02       # 止盈比例
    stop_loss: 0.05         # 止损比例
    
# 交易设置
trading:
  commission: 0.001         # 手续费率
  slippage: 0.0005          # 滑点
  leverage: 1               # 杠杆倍数
  position_size: 0.1        # 仓位大小（占总资金比例）
  max_position_size: 0.5    # 最大仓位大小
  
# 风控设置
risk:
  max_drawdown: 0.2         # 最大回撤
  max_loss_per_trade: 0.05  # 单笔最大亏损
  max_loss_per_day: 0.1     # 单日最大亏损
  max_open_positions: 5     # 最大持仓数量
  
# 输出设置
output:
  save_trades: true         # 是否保存交易记录
  save_performance: true    # 是否保存绩效指标
  save_plots: true          # 是否保存图表
  output_dir: "./results"   # 输出目录
  plot_format: "png"        # 图表格式
  
# 日志设置
logging:
  level: "INFO"             # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/backtest.log"  # 日志文件
  console: true             # 是否输出到控制台
  
# 并行设置
parallel:
  enabled: false            # 是否启用并行
  n_jobs: 4                 # 并行任务数
  
# 其他设置
misc:
  random_seed: 42           # 随机种子
  verbose: true             # 是否输出详细信息
