# 实盘交易配置文件
# 遵循RIPER-5原则：风险优先、最小侵入、可预期性、可扩展性、真实可评估

# 基本设置
basic:
  mode: "paper"              # 交易模式: "paper"(模拟) 或 "live"(实盘)
  symbols:                   # 交易对列表
    - "BTC/USDT"
    - "ETH/USDT"
  timeframes:                # 时间框架列表
    - "1h"
    - "4h"
    - "1d"
  
# 交易所设置
exchanges:
  binance:
    enabled: true            # 是否启用
    api_key: ""              # API密钥
    secret: ""               # API密钥
    passphrase: ""           # API密钥(仅某些交易所需要)
    sandbox: true            # 是否使用测试环境
    testnet: true            # 是否使用测试网络
    futures: false           # 是否使用合约
    leverage: 1              # 杠杆倍数
    
  okx:
    enabled: false           # 是否启用
    api_key: ""              # API密钥
    secret: ""               # API密钥
    passphrase: ""           # API密钥
    sandbox: true            # 是否使用测试环境
    testnet: true            # 是否使用测试网络
    futures: false           # 是否使用合约
    leverage: 1              # 杠杆倍数
    
# 策略设置
strategies:
  - name: "Martingale"       # 策略名称
    symbols: ["BTC/USDT"]    # 交易对
    timeframe: "1m"          # 时间框架
    enabled: true            # 是否启用
    params:                  # 策略参数
      base_order_size: 0.001 # 基础订单大小
      multiplier: 2.0        # 倍数
      max_orders: 10         # 最大订单数
      take_profit: 0.01      # 止盈比例
      stop_loss: 0.05        # 止损比例
      
  - name: "GridStrategy"     # 策略名称
    symbols: ["ETH/USDT"]    # 交易对
    timeframe: "5m"          # 时间框架
    enabled: false           # 是否启用
    params:                  # 策略参数
      grid_size: 0.01        # 网格大小
      grid_levels: 10        # 网格层数
      order_size: 0.01       # 订单大小
      take_profit: 0.02      # 止盈比例
      stop_loss: 0.05        # 止损比例
      
# 交易设置
trading:
  position_size: 0.1         # 仓位大小（占总资金比例）
  max_position_size: 0.5     # 最大仓位大小
  order_type: "limit"        # 订单类型: "market" 或 "limit"
  price_offset: 0.001        # 限价单价格偏移
  order_timeout: 300         # 订单超时时间(秒)
  retry_count: 3             # 重试次数
  retry_interval: 5          # 重试间隔(秒)
  
# 风控设置
risk:
  max_drawdown: 0.2          # 最大回撤
  max_loss_per_trade: 0.05   # 单笔最大亏损
  max_loss_per_day: 0.1      # 单日最大亏损
  max_open_positions: 5      # 最大持仓数量
  daily_loss_reset_time: "00:00"  # 每日亏损重置时间
  emergency_stop: false      # 紧急停止开关
  
# 资金管理
capital:
  max_capital_usage: 0.8     # 最大资金使用比例
  reserve_capital: 0.2       # 预留资金比例
  min_order_size: 0.001      # 最小订单大小
  max_order_size: 0.1        # 最大订单大小
  
# 监控设置
monitoring:
  enabled: true              # 是否启用监控
  check_interval: 60         # 检查间隔(秒)
  alert_threshold: 0.05      # 警报阈值
  notification_methods:      # 通知方式
    - "email"
    - "webhook"
  email:
    smtp_server: ""          # SMTP服务器
    smtp_port: 587           # SMTP端口
    username: ""             # 邮箱用户名
    password: ""             # 邮箱密码
    recipients:              # 收件人列表
      - ""
  webhook:
    url: ""                  # Webhook URL
    
# 数据设置
data:
  save_data: true            # 是否保存数据
  data_dir: "./data"         # 数据目录
  save_interval: 3600        # 保存间隔(秒)
  
# 日志设置
logging:
  level: "INFO"              # 日志级别
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/live.log"    # 日志文件
  console: true              # 是否输出到控制端
  max_file_size: 10485760    # 最大文件大小(字节)
  backup_count: 5            # 备份文件数量
  trade_log: true            # 是否记录交易日志
  trade_log_file: "./logs/trades.log"  # 交易日志文件
  
# 报告设置
reporting:
  enabled: true              # 是否启用报告
  interval: 86400            # 报告间隔(秒)
  save_reports: true         # 是否保存报告
  report_dir: "./reports"    # 报告目录
  include_charts: true       # 是否包含图表
  
# 性能设置
performance:
  max_cpu_usage: 80          # 最大CPU使用率(%)
  max_memory_usage: 80       # 最大内存使用率(%)
  thread_pool_size: 4        # 线程池大小
  
# 其他设置
misc:
  timezone: "UTC"            # 时区
  verbose: true              # 是否输出详细信息
  debug: false               # 是否启用调试模式
